Repository GSG-FC02/PalArt-Gallery, pull requests merged in 2021-03, with the labels that each got.

#12 Creating aboutus section
  css/media.css
  css/style.css
  index.html
Labels: approved

#11 create a header with style
  css/media.css
  css/style.css
  index.html
Labels: changes-request

#10 Contact Us section
  README.md
  css/font-awesome.min.css
  css/media.css
  css/style.css
  fonts/FontAwesome.otf
  fonts/fontawesome-webfont.eot
  fonts/fontawesome-webfont.svg
  fonts/fontawesome-webfont.ttf
  fonts/fontawesome-webfont.woff
  fonts/fontawesome-webfont.woff2
  index.html
Labels: approved

#13 add gallery section code (html-style-media)
  css/media.css
  css/style.css
  index.html
Labels: approved

#14 add footer code
  css/media.css
  css/style.css
  index.html
Labels: approved

#15 add our team section
  css/media.css
  css/style.css
  images/n.png
  index.html
Labels: approved

#20 README file is finish
  README.md
Labels: changes-request

#19 header of the second gallery page , with about the painters section
  .vscode/settings.json
  css/gal-style.css
  css/media.css
  css/style.css
  gal.html
  index.html
Labels: awaiting-review

#22 last-header-branch
  css/media.css
  css/style.css
  index.html
Labels: approved

#21 final about-us section
  css/media.css
  css/style.css
Labels: changes-request
